trigger: none

pool: Infra_1

variables:
  TF_WORKING_DIR: '$(System.DefaultWorkingDirectory)/AKS'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Step 1: Terraform Init
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(TF_WORKING_DIR)'
    backendServiceArm: 'Loveneesh_23'
    backendAzureRmResourceGroupName: 'rk-rg'
    backendAzureRmStorageAccountName: 'stgstate'
    backendAzureRmContainerName: 'terraformstate'
    backendAzureRmKey: 'state.tf'
    commandOptions: '-input=false'

# Step 2: Terraform Validate
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(TF_WORKING_DIR)'

# Step 3: Terraform Plan
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(TF_WORKING_DIR)'
    environmentServiceNameAzureRM: 'Loveneesh_23'
    commandOptions: '-out=tfplan -input=false'

# Step 4: Terraform Apply
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(TF_WORKING_DIR)'
    environmentServiceNameAzureRM: 'Loveneesh_23'
    commandOptions: 'tfplan -input=false -auto-approve'
