
trigger: none

pool:
  name: love2   # self-hosted agent

variables:
  TF_WORKING_DIR: '$(System.DefaultWorkingDirectory)/AKS'

steps:

# 1️⃣ Verify Terraform installation
- script: |
    echo "Checking Terraform installation on agent..."
    where terraform
    terraform version
  displayName: 'Verify Terraform Installation'

# 2️⃣ Terraform Init
- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(TF_WORKING_DIR)'
    backendServiceArm: 'Loveneesh_2'
    backendAzureRmResourceGroupName: 'rg-aks'
    backendAzureRmStorageAccountName: 'love12345'
    backendAzureRmContainerName: 'loveneesh'
    backendAzureRmKey: 'love.tfstate'
    backendAzureRmUseAzureAdAuth: true

# 3️⃣ Terraform Fmt
- task: TerraformTask@5
  displayName: 'Terraform Fmt'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(TF_WORKING_DIR)'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'Loveneesh_2'

# 4️⃣ Terraform Validate
- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(TF_WORKING_DIR)'
    environmentServiceNameAzureRM: 'Loveneesh_2'

# 5️⃣ Terraform Plan
- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(TF_WORKING_DIR)'
    environmentServiceNameAzureRM: 'Loveneesh_2'
