trigger:
  branches:
    include:
      - feature/*
      - main

pool: love2  # self-hosted agent

steps:
- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    terraformExe: '$(TF_EXE_PATH)'
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'C:\Love_48\2\s'
    backendServiceArm: 'loveneesh'
    backendAzureRmResourceGroupName: 'rg-aks'
    backendAzureRmStorageAccountName: 'love12345'
    backendAzureRmContainerName: 'loveneesh'
    backendAzureRmKey: 'love.tfstate'
    commandOptions: '-input=false -migrate-state'   # ✅ auto answer "yes"

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    terraformExe: '$(TF_EXE_PATH)'
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'C:\Love_48\2\s'
    environmentServiceNameAzureRM: 'loveneesh'
    ensureBackend: true
