trigger: none


pool: Infra_1  # self-hosted agent

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Loveneesh_23'
    backendAzureRmResourceGroupName: 'rk-rg'
    backendAzureRmStorageAccountName: 'stgstate'
    backendAzureRmContainerName: 'terraformstate'
    backendAzureRmKey: 'state.tf'
