# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:love2
 

jobs:
- job : Init
  displayName: init job
  pool: love2

  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'


  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'Loveneesh'
      backendAzureRmResourceGroupName: 'Loveaks-resource-group'
      backendAzureRmStorageAccountName: 'love12345'
      backendAzureRmContainerName: 'loveneesh'
      backendAzureRmKey: 'state.tf'

    

