trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_WORKING_DIR: '$(System.DefaultWorkingDirectory)/AKS'

stages:
# ------------------ Stage 1: Validate ------------------
- stage: Validate
  displayName: "Validate Terraform Code"
  jobs:
  - job: Validate
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # Install Terraform CLI
      - script: |
          curl -LO https://releases.hashicorp.com/terraform/1.7.7/terraform_1.7.7_linux_amd64.zip
          unzip terraform_1.7.7_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
        displayName: "Install Terraform CLI"

      - script: terraform fmt -check
        displayName: "Terraform Format Check"
        workingDirectory: $(TF_WORKING_DIR)

      - script: terraform validate
        displayName: "Terraform Validate"
        workingDirectory: $(TF_WORKING_DIR)

# ------------------ Stage 2: Plan ------------------
- stage: Plan
  displayName: "Terraform Plan"
  dependsOn: Validate
  jobs:
  - job: Plan
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: terraform init
        displayName: "Terraform Init"
        workingDirectory: $(TF_WORKING_DIR)

      - script: terraform plan -out=tfplan
        displayName: "Terraform Plan"
        workingDirectory: $(TF_WORKING_DIR)

# ------------------ Stage 3: Apply ------------------
- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: Plan
  jobs:
  - job: Apply
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: terraform apply -auto-approve tfplan
        displayName: "Terraform Apply"
        workingDirectory: $(TF_WORKING_DIR)
