trigger:
  branches:
    include:
      - feature/*
      - main

pool: love2

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/AKS'
    backendServiceArm: 'loveneesh' 
    backendAzureRmResourceGroupName: 'rg-aks'
    backendAzureRmStorageAccountName: 'love12345'
    backendAzureRmContainerName: 'loveneesh'
    backendAzureRmKey: 'love.tfstate'








