trigger: none   # Manually run

pool:
  name: love2   # Self-hosted agent

variables:
  TF_WORKING_DIR: '$(System.DefaultWorkingDirectory)/AKS'

steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: '1.13.0'

  - task: TerraformTask@5
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(TF_WORKING_DIR)'
      environmentServiceNameAzureRM: 'Loveneesh_2'
      backendServiceArm: 'Loveneesh_2'
      backendAzureRmResourceGroupName: 'rg-aks'
      backendAzureRmStorageAccountName: 'love12345'
      backendAzureRmContainerName: 'loveneesh'
      backendAzureRmKey: 'love.tfstate'

  - task: TerraformTask@5
    displayName: 'Terraform Fmt'
    inputs:
      provider: 'azurerm'
      command: 'custom'
      workingDirectory: '$(TF_WORKING_DIR)'
      outputTo: 'console'
      customCommand: 'fmt'
      environmentServiceNameAzureRM: 'Loveneesh_2'

  - task: TerraformTask@5
    displayName: 'Terraform Validate'
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(TF_WORKING_DIR)'

  - task: TerraformTask@5
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(TF_WORKING_DIR)'
      environmentServiceNameAzureRM: 'Loveneesh_2'
