name: Azure Login Test

on:
  workflow_dispatch:  # Manual trigger

jobs:
  azure-login:
    runs-on: self-hosted   # ✅ Corrected

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login with Service Principal
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          }

    - name: Verify Azure CLI Login
      run: az account show
